### ISSUE TITLE
Crash bootstraping gitlab repository

### ISSUE THREAD

**Issue by enribd** [fluxcd/flux2#1383]
### Describe the bug

Tried to bootstrap a cluster using the `flux bootstrap gitlab` command but it crashed. The repository exists and was previously used with flux without problem. Also tried to bootstrap a brand new repository in gitlab. I exported the GITLAB_TOKEN variable with read and write permissions, I used the same token with flux without problems.

Flux cli binary versions tried (same error was reported for everyone of them): 0.13.2, 0.13.1, 0.13.0, 0.12.3

### To Reproduce

Steps to reproduce the behaviour:

1. Provide Flux install instructions
```cli
↳ flux bootstrap gitlab \
  --owner="myproject/path" \
  --repository="gitops" \
  --branch="master" \
  --components=source-controller,kustomize-controller,helm-controller,notification-controller \
  --components-extra=image-reflector-controller,image-automation-controller \
  --path="cluster/namespaces" \
  --token-auth

► connecting to gitlab.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x18048e8]

goroutine 1 [running]:
github.com/fluxcd/go-git-providers/gitprovider/cache.(*cacheRoundtripper).RoundTrip(0xc0007ce0b0, 0xc0007d4800, 0xc0007ce0b0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/fluxcd/go-git-providers@v0.0.3/gitprovider/cache/httpcache.go:71 +0xc8
net/http.send(0xc0007d4800, 0x21660a0, 0xc0007ce0b0, 0x0, 0x0, 0x0, 0xc0007ce008, 0xc000636188, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.16.3/x64/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0004734a0, 0xc0007d4800, 0x0, 0x0, 0x0, 0xc0007ce008, 0x0, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.16.3/x64/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0004734a0, 0xc0007d4800, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.3/x64/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.16.3/x64/src/net/http/client.go:585
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc00040c150, 0xc0004f08d0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.6.8/client.go:591 +0x16e
github.com/xanzy/go-gitlab.(*Client).Do(0xc0005aa700, 0xc0004f08d0, 0x1bcd9e0, 0xc0004fd800, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/xanzy/go-gitlab@v0.43.0/gitlab.go:640 +0x30d
github.com/xanzy/go-gitlab.(*ProjectsService).GetProject(0xc0007ce288, 0x1b6cb40, 0xc0004f0890, 0xc0001024e0, 0xc000636818, 0x1, 0x1, 0x0, 0x0, 0x2169cc0, ...)
        /home/runner/go/pkg/mod/github.com/xanzy/go-gitlab@v0.43.0/projects.go:412 +0x1d4
github.com/fluxcd/go-git-providers/gitlab.(*gitlabClientImpl).GetGroupProject(0xc0004f07c0, 0x21a42d8, 0xc0006b3740, 0x7ffce5da3e0a, 0x1b, 0x7ffce5da3e33, 0x6, 0x7ffce5da3e33, 0x6, 0x1ecb495)
        /home/runner/go/pkg/mod/github.com/fluxcd/go-git-providers@v0.0.3/gitlab/gitlabclient.go:173 +0x1e5
github.com/fluxcd/go-git-providers/gitlab.(*OrgRepositoriesClient).Get(0xc0007ce338, 0x21a42d8, 0xc0006b3740, 0x1ecb495, 0xa, 0x7ffce5da3e0a, 0x1b, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/fluxcd/go-git-providers@v0.0.3/gitlab/client_repositories_org.go:44 +0x116
github.com/fluxcd/flux2/internal/bootstrap.(*GitProviderBootstrapper).reconcileOrgRepository(0xc0002423c0, 0x21a42d8, 0xc0006b3740, 0xc000068000, 0xc000637098, 0x48471b, 0x7f88ca5bfca0)
        /home/runner/work/flux2/flux2/internal/bootstrap/bootstrap_provider.go:276 +0x442
github.com/fluxcd/flux2/internal/bootstrap.(*GitProviderBootstrapper).ReconcileRepository(0xc0002423c0, 0x21a42d8, 0xc0006b3740, 0x7f88ca5bfca0, 0xc0002423c0)
        /home/runner/work/flux2/flux2/internal/bootstrap/bootstrap_provider.go:218 +0x24c
github.com/fluxcd/flux2/internal/bootstrap.Run(0x21a42d8, 0xc0006b3740, 0x21ad9b8, 0xc0002423c0, 0xc0003edaa0, 0x1d, 0x1f00967, 0x28, 0xc000059c68, 0x7, ...)
        /home/runner/work/flux2/flux2/internal/bootstrap/bootstrap.go:85 +0x478
main.bootstrapGitLabCmdRun(0x2f718e0, 0xc0003c93b0, 0x0, 0x7, 0x0, 0x0)
        /home/runner/work/flux2/flux2/cmd/flux/bootstrap_gitlab.go:267 +0x12ce
github.com/spf13/cobra.(*Command).execute(0x2f718e0, 0xc0003c9180, 0x7, 0x7, 0x2f718e0, 0xc0003c9180)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2f70140, 0x0, 0x4063c5, 0xc0000ae058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /home/runner/work/flux2/flux2/cmd/flux/main.go:132 +0x4f
```

### Expected behavior

Create/update the manifests in the git repository "cluster/namespaces/flux-system" folder. Also tried with a non-existent git repository so flux should create it, but the error is the same.

### Additional context

- Kubernetes version: 1.19.6-eks
- Git provider: Gitlab (gitlab.com)
- Container registry provider: default from flux cli

Below please provide the output of the following commands:

```cli
↳ flux --version && flux check
flux version 0.13.2
► checking prerequisites
✔ kubectl 1.20.5 >=1.18.0-0
✔ Kubernetes 1.19.6-eks-49a6c0 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.9.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.9.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.13.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.12.1
✔ all checks passed
```

Thanks in advance you for your help!

**Comment by stefanprodan** [comment]
@enribd you can either build the CLI from my PR or use [flux bootstrap git](https://fluxcd.io/docs/guides/installation/#generic-git-server) as a workaround until the fix gets released.

**Comment by enribd** [comment]
I'll wait for the next release, thanks! :smiley:

**Comment by joberdick-rcd** [comment]
Hi @stefanprodan, I still got this on 0.16.1. Is that expected?
