### ISSUE TITLE
image reflector crashlooping

### ISSUE THREAD

**Issue by durprasa** [fluxcd/flux2#1742]
I see this crash that is occurring in image reflector probably due to a bad image policy. Should be gracefully handled though?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x16138f5]

goroutine 531 [running]:
github.com/fluxcd/image-reflector-controller/internal/policy.(*SemVer).Latest(0x0, 0xc014b14000, 0x38, 0x40, 0xc00cf2a4a0, 0x0, 0x0, 0x0)
        /workspace/internal/policy/semver.go:55 +0x135
github.com/fluxcd/image-reflector-controller/controllers.(*ImagePolicyReconciler).Reconcile(0xc00bfb4000, 0x1ba9fb8, 0xc0147f83f0, 0xc00c2b7ab0, 0xb, 0xc00c2b7a90, 0x10, 0xc0147f8300, 0x0, 0x0, ...)
        /workspace/controllers/imagepolicy_controller.go:140 +0x11a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00bf90e60, 0x1ba9f10, 0xc00b917140, 0x17e5800, 0xc00050ab20)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00bf90e60, 0x1ba9f10, 0xc00b917140, 0x1a3af00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000325350, 0xc00bf90e60, 0x1ba9f10, 0xc00b917140)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:210 +0x425

**Comment by stefanprodan** [comment]
@durprasa please fill in the bug report form, which flux version, which controllers versions, which cluster version, which objects should we use to reproduce this.

**Comment by durprasa** [comment]
> 
> 
> @durprasa please fill in the bug report form, which flux version, which controllers versions, which cluster version, which objects should we use to reproduce this.

Sure.. I will have to figure out if my assumption was right or not. which is when the image policy as below
`apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: "{{ .Release.Namespace }}-{{ .Release.Name }}"
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: "{{ .Release.Namespace }}-{{ .Release.Name }}"
  filterTags:
    pattern: "^v(?P<semver>.*)"
    extract: "$semver"
  policy:
    semver:
      range: ">={{ .Values.image.tag }}"`
      
 and if the tag doesn't match the pattern then this behavior is exhibited I believe. However, I will try to confirm and update with little more details.
flux version 0.16.1
ghcr.io/fluxcd/image-reflector-controller:v0.11.0
