### ISSUE TITLE
Kustomize controller panic

### ISSUE THREAD

**Issue by tingold** [fluxcd/flux2#2803]
### Describe the bug

Updated a value in a sops-encoded secret and forced a reconcile via CLI.  CLI operation timed out and looking at the container logs (below) the kustomize controller appears to panic with the message "panic: number of previous names, number of previous namespaces, number of previous kinds not equal". 

I manually applied the secret value without issue however the controller continues to panic and restart

### Steps to reproduce

I suspect this is something very specific to the env so doubt this will recreate as I've changed secret values before without issue

1. Update secret value
2. Watch controller panic

### Expected behavior

I don't see any reason to not apply the changed secret -- works fine with kubectl.

### OS / Distro

OSX but N/A

### Flux version

➜ flux version flux: v0.30.2 helm-controller: v0.17.1 image-automation-controller: v0.20.1 image-reflector-controller: v0.16.0 kustomize-controller: v0.21.1 notification-controller: v0.22.2 source-controller: v0.21.2

### Flux check

➜ flux check
► checking prerequisites
✔ Kubernetes 1.21.12-eks-a64ea69 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Git provider

Github

### Additional context

Flux logs doesn't provide anything specific to the panic.... the image is ghcr.io/fluxcd/kustomize-controller:v0.21.1

Controller logs:

```{"level":"info","ts":"2022-06-02T14:18:32.674Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2022-06-02T14:18:32.674Z","logger":"setup","msg":"starting manager"}
{"level":"info","ts":"2022-06-02T14:18:32.675Z","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":"2022-06-02T14:18:32.675Z","msg":"Starting server","kind":"health probe","addr":"[::]:9440"}
I0602 14:18:32.775749       7 leaderelection.go:248] attempting to acquire leader lease flux-system/kustomize-controller-leader-election...
I0602 14:19:11.924795       7 leaderelection.go:258] successfully acquired lease flux-system/kustomize-controller-leader-election
{"level":"info","ts":"2022-06-02T14:19:11.924Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: *v1beta2.Kustomization"}
{"level":"info","ts":"2022-06-02T14:19:11.925Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: *v1beta1.GitRepository"}
{"level":"info","ts":"2022-06-02T14:19:11.925Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: *v1beta1.Bucket"}
{"level":"info","ts":"2022-06-02T14:19:11.925Z","logger":"controller.kustomization","msg":"Starting Controller","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization"}
{"level":"info","ts":"2022-06-02T14:19:12.026Z","logger":"controller.kustomization","msg":"Starting workers","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","worker count":4}
{"level":"info","ts":"2022-06-02T14:19:15.024Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"plastic-frontend-prod-kustomization","namespace":"flux-system","output":{"Namespace/plastic-frontend":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:19:15.100Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"plastic-frontend-dev-kustomization","namespace":"flux-system","output":{"Namespace/plastic-frontend":"configured"}}```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tingold** [comment]
Logs got cut off -- here is the complete stack
```
{"level":"info","ts":"2022-06-02T14:28:41.326Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: *v1beta2.Kustomization"}
{"level":"info","ts":"2022-06-02T14:28:41.326Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: *v1beta1.GitRepository"}
{"level":"info","ts":"2022-06-02T14:28:41.326Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: *v1beta1.Bucket"}
{"level":"info","ts":"2022-06-02T14:28:41.326Z","logger":"controller.kustomization","msg":"Starting Controller","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization"}
{"level":"info","ts":"2022-06-02T14:28:41.427Z","logger":"controller.kustomization","msg":"Starting workers","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","worker count":4}
{"level":"info","ts":"2022-06-02T14:28:42.069Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-add-on-kustomization","namespace":"flux-system","output":{"Secret/flux-system/dockerconfigjson-github-com":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:42.082Z","logger":"controller.kustomization","msg":"Reconciliation finished in 654.184772ms, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-add-on-kustomization","namespace":"flux-system","revision":"main/db096af3a7a9583595992f08a6d13ec30d01039b"}
{"level":"info","ts":"2022-06-02T14:28:43.099Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-frontend-kustomization-prod","namespace":"flux-system","output":{"Deployment/news/news-frontend-deployment-prod":"unchanged","IngressRoute/news/news-frontend-ingress-prod":"unchanged","Secret/news/dockerconfigjson-github-com-prod":"unchanged","Service/news/news-frontend-service-prod":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.115Z","logger":"controller.kustomization","msg":"Reconciliation finished in 1.687377151s, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-frontend-kustomization-prod","namespace":"flux-system","revision":"main/3a7de5ba4e1dcdfd8fda4914bab1c7c8f5ae6994"}
{"level":"info","ts":"2022-06-02T14:28:43.311Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"oauth2-proxy-kustomization","namespace":"flux-system","output":{"Namespace/oauth2-proxy":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.350Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-kustomization-prod","namespace":"flux-system","output":{"Namespace/news":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.389Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-kustomization-dev","namespace":"flux-system","output":{"Namespace/news":"configured"}}
{"level":"info","ts":"2022-06-02T14:28:43.393Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"oauth2-proxy-kustomization","namespace":"flux-system","output":{"Deployment/oauth2-proxy/oauth2-proxy-deployment":"unchanged","Secret/oauth2-proxy/oauthconf-secret":"unchanged","Service/oauth2-proxy/oauth2-proxy-service":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.408Z","logger":"controller.kustomization","msg":"Reconciliation finished in 291.884711ms, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"oauth2-proxy-kustomization","namespace":"flux-system","revision":"main/db096af3a7a9583595992f08a6d13ec30d01039b"}
{"level":"info","ts":"2022-06-02T14:28:43.470Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"debug-kustomization","namespace":"flux-system","output":{"Namespace/debug":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.571Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"debug-kustomization","namespace":"flux-system","output":{"Deployment/debug/httpbin":"unchanged","IngressRoute/debug/httpbin-ingress":"unchanged","Middleware/debug/test-auth":"unchanged","Middleware/debug/test-strip-prefix":"unchanged","Service/debug/httpbin-service":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.586Z","logger":"controller.kustomization","msg":"Reconciliation finished in 175.981868ms, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"debug-kustomization","namespace":"flux-system","revision":"main/db096af3a7a9583595992f08a6d13ec30d01039b"}
{"level":"info","ts":"2022-06-02T14:28:43.826Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-kustomization-dev","namespace":"flux-system","output":{"ConfigMap/news/elastic-configmap-dev-bd478ft2hd":"unchanged","Deployment/news/index-service-deployment-dev":"unchanged","Deployment/news/kibana-deployment-dev":"unchanged","Deployment/news/news-deployment-dev":"unchanged","HelmRelease/news/elastic-news-deployment-dev":"unchanged","HelmRepository/news/elasticsearch-charts-dev":"unchanged","IngressRoute/news/elastic-ingress-dev":"unchanged","IngressRoute/news/news-index-ingress-dev":"unchanged","IngressRoute/news/news-ingress-dev":"unchanged","Secret/news/dockerconfigjson-github-com-dev":"configured","Secret/news/legacy-api-google-secret-dev":"unchanged","Secret/news/legacy-api-secret-dev":"unchanged","Service/news/article-api-service-dev":"unchanged","Service/news/index-service-dev":"unchanged","Service/news/kibana-service-dev":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.842Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","output":{"CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/buckets.source.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/imagepolicies.image.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/imagerepositories.image.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/imageupdateautomations.image.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/providers.notification.toolkit.fluxcd.io":"unchanged","CustomResourceDefinition/receivers.notification.toolkit.fluxcd.io":"unchanged","Namespace/flux-system":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.848Z","logger":"controller.kustomization","msg":"Reconciliation finished in 1.755793641s, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-kustomization-dev","namespace":"flux-system","revision":"main/ca2d06e0dad282c00084c3c895711746db6e6b7a"}
{"level":"info","ts":"2022-06-02T14:28:43.915Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-kustomization-prod","namespace":"flux-system","output":{"CronJob/news/article-cron-prod":"unchanged","Deployment/news/index-service-deployment-prod":"unchanged","Deployment/news/legacy-deployment-prod":"unchanged","Deployment/news/legacy-deployment-web-prod":"unchanged","Deployment/news/legacy-deployment-worker-prod":"unchanged","Deployment/news/news-deployment-prod":"unchanged","IngressRoute/news/index-ingress-prod":"unchanged","IngressRoute/news/news-ingress-prod":"unchanged","IngressRoute/news/wtl-ingress-prod":"unchanged","Middleware/news/cors-prod":"unchanged","Middleware/news/rewrite-index-prod":"unchanged","Secret/news/dockerconfigjson-github-com-prod":"configured","Secret/news/legacy-api-google-secret-prod":"unchanged","Secret/news/legacy-api-secret-prod":"unchanged","Service/news/article-api-service-prod":"unchanged","Service/news/index-service-prod":"unchanged","Service/news/redis-service-prod":"unchanged","Service/news/wtl-service-prod":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:43.981Z","logger":"controller.kustomization","msg":"Reconciliation finished in 2.55378396s, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-kustomization-prod","namespace":"flux-system","revision":"main/ca2d06e0dad282c00084c3c895711746db6e6b7a"}
{"level":"info","ts":"2022-06-02T14:28:44.027Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"monitoring-stack","namespace":"flux-system","output":{"Namespace/monitoring":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:44.441Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"monitoring-stack","namespace":"flux-system","output":{"ConfigMap/monitoring/ambassador-grafana-dashboards-2tt4ftf4b8":"unchanged","ConfigMap/monitoring/flux-grafana-dashboards-656chmc452":"unchanged","ConfigMap/monitoring/helm-prometheus-values-configmap-hgm4btgc4t":"unchanged","HelmRelease/monitoring/kube-prometheus-stack":"unchanged","HelmRepository/monitoring/prometheus-community":"unchanged","PodMonitor/monitoring/flux-system":"unchanged","ServiceMonitor/monitoring/ambassador-monitor":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:44.535Z","logger":"controller.kustomization","msg":"Reconciliation finished in 653.772599ms, next run in 1h0m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"monitoring-stack","namespace":"flux-system","revision":"main/8f2dd30e1356318814175994eccf52575f1fb2b3"}
{"level":"info","ts":"2022-06-02T14:28:44.600Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"plastic-kustomization-dev","namespace":"flux-system","output":{"Namespace/plastic-api":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:44.824Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"plastic-kustomization-dev","namespace":"flux-system","output":{"Deployment/plastic-api/plastic-deployment-dev":"unchanged","Deployment/plastic-api/postgis-deployment-dev":"unchanged","IngressRoute/plastic-api/plastic-api-e7e-ingress-dev":"unchanged","PersistentVolumeClaim/plastic-api/postgis-plastic-pv-claim-dev":"unchanged","Secret/plastic-api/dockerconfigjson-github-com-dev":"unchanged","Secret/plastic-api/postgis-secrets-dev":"unchanged","Service/plastic-api/plastic-service-dev":"unchanged","Service/plastic-api/postgis-dev":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:44.845Z","logger":"controller.kustomization","msg":"Reconciliation finished in 861.641473ms, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"plastic-kustomization-dev","namespace":"flux-system","revision":"main/a06a523e43036733a3ed675a3a2ce18ddaa7d640"}
{"level":"info","ts":"2022-06-02T14:28:44.881Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-frontend-kustomization-dev","namespace":"flux-system","output":{"Deployment/news/news-frontend-deployment-dev":"unchanged","IngressRoute/news/news-frontend-ingress-dev":"unchanged","Secret/news/dockerconfigjson-github-com-dev":"configured","Service/news/news-frontend-service-dev":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:44.898Z","logger":"controller.kustomization","msg":"Reconciliation finished in 362.119662ms, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-frontend-kustomization-dev","namespace":"flux-system","revision":"main/3a7de5ba4e1dcdfd8fda4914bab1c7c8f5ae6994"}
panic: number of previous names, number of previous namespaces, number of previous kinds not equal

goroutine 378 [running]:
{"level":"info","ts":"2022-06-02T14:28:44.881Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-frontend-kustomization-dev","namespace":"flux-system","output":{"Deployment/news/news-frontend-deployment-dev":"unchanged","IngressRoute/news/news-frontend-ingress-dev":"unchanged","Secret/news/dockerconfigjson-github-com-dev":"configured","Service/news/news-frontend-service-dev":"unchanged"}}
{"level":"info","ts":"2022-06-02T14:28:44.898Z","logger":"controller.kustomization","msg":"Reconciliation finished in 362.119662ms, next run in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"news-frontend-kustomization-dev","namespace":"flux-system","revision":"main/3a7de5ba4e1dcdfd8fda4914bab1c7c8f5ae6994"}
panic: number of previous names, number of previous namespaces, number of previous kinds not equal

goroutine 378 [running]:
sigs.k8s.io/kustomize/api/resource.(*Resource).PrevIds(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/resource/resource.go:431
sigs.k8s.io/kustomize/api/resource.(*Resource).OrgId(0xc000119c70)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/resource/resource.go:414 +0x154
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).determineFilters(0xc000b14728, {0xc0008d5180, 0xe, 0xc000b89200})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/internal/accumulator/namereferencetransformer.go:120 +0x89
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc00109b8f0, {0x21f1780, 0xc000fdc6f0})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/internal/accumulator/namereferencetransformer.go:52 +0x5d
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/internal/accumulator/resaccumulator.go:142
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0x0)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/internal/accumulator/resaccumulator.go:168 +0xc5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0001180f0)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/internal/target/kusttarget.go:142 +0x8f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/internal/target/kusttarget.go:118
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000b14ef0, {0x21d3360, 0x319ba10}, {0xc0011c6540, 0x2d})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.2/krusty/kustomizer.go:89 +0x39c
github.com/fluxcd/kustomize-controller/controllers.buildKustomization({0x21d3360, 0x319ba10}, {0xc0011c6540, 0x2d})
	/workspace/controllers/kustomization_generator.go:252 +0x1c5
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).build(_, {_, _}, {{{0x1a11713, 0xd}, {0xc0018e8090, 0x23}}, {{0xc000057878, 0x17}, {0x0, ...}, ...}, ...}, ...)
	/workspace/controllers/kustomization_controller.go:652 +0x214
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).reconcile(_, {_, _}, {{{0x1a11713, 0xd}, {0xc0018e8090, 0x23}}, {{0xc000057878, 0x17}, {0x0, ...}, ...}, ...}, ...)
	/workspace/controllers/kustomization_controller.go:370 +0x925
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).Reconcile(0xc0001cabd0, {0x2189088, 0xc004d89890}, {{{0xc0003425d0, 0x1d27800}, {0xc000057878, 0x30}}})
	/workspace/controllers/kustomization_controller.go:263 +0x178c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00070e210, {0x2189088, 0xc004d897d0}, {{{0xc0003425d0, 0x1d27800}, {0xc000057878, 0x413dd4}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00070e210, {0x2188fe0, 0xc0005167c0}, {0x1c0f620, 0xc000560640})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00070e210, {0x2188fe0, 0xc0005167c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
 ```

**Comment by stefanprodan** [comment]
Seem related to https://github.com/kubernetes-sigs/kustomize/issues/641

**Comment by stefanprodan** [comment]
We've added recovery from panic some time ago, please update your control plane.

**Comment by tingold** [comment]
That seems to have fixed it thx
