### ISSUE TITLE
kustomization error

### ISSUE THREAD

**Issue by plockaby** [fluxcd/flux2#3458]
### Describe the bug

I added this to the `exclusionList` of an `Alert`:

```
"ImageRepository\.image\.toolkit\.fluxcd\.io \".*\" not found"
```

And that caused the `kustomization-controller` to fail with this:

```
{"level":"error","ts":"2023-01-03T04:56:21.911Z","msg":"Reconciler error","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"flux-system","namespace":"flux-system"},"namespace":"flux-system","name":"flux-system","reconcileID":"f05372d4-cb4d-409e-80dd-d185b42f009e","error":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
E0103 04:56:45.994483       8 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 309 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1eaf2e0?, 0x380e010})
    k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
    sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:110 +0xb9
panic({0x1eaf2e0, 0x380e010})
    runtime/panic.go:884 +0x212
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.handleErr(0xc000959928)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/yaml.go:304 +0x6d
panic({0x1eaf2e0, 0x380e010})
    runtime/panic.go:884 +0x212
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_split_stem_comment(0xc0005f6800, 0x38)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/parserc.go:789 +0x38
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_parse_block_sequence_entry(0xc0005f6800, 0xc0005f6ab0, 0x70?)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/parserc.go:703 +0x1fb
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_state_machine(0x0?, 0x5?)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/parserc.go:179 +0xcf
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.yaml_parser_parse(0xc000dd25a0?, 0x219edcc?)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/parserc.go:129 +0x8c
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).peek(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:103 +0x30
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).sequence(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:258 +0x115
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:154 +0xeb
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parseChild(0xc0005f6800?, 0xc000dc0320)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:194 +0x25
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).mapping(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:285 +0x1d7
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:152 +0x105
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parseChild(0xc0005f6800?, 0xc000dafb80)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:194 +0x25
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).mapping(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:285 +0x1d7
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:152 +0x105
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parseChild(...)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:194
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).document(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:203 +0x85
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*parser).parse(0xc0005f6800)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/decode.go:156 +0xae
sigs.k8s.io/kustomize/kyaml/internal/forked/github.com/go-yaml/yaml.(*Decoder).Decode(0xc000d05f90, {0x1fedce0?, 0xc000dafa40})
    sigs.k8s.io/kustomize/kyaml@v0.13.9/internal/forked/github.com/go-yaml/yaml/yaml.go:123 +0x136
sigs.k8s.io/kustomize/kyaml/kio.(*ByteReader).decode(0xc000959d68, {0xc000b00000, 0x430}, 0x26a86a0?, 0xc0008ec7b0?)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/kio/byteio_reader.go:292 +0x79
sigs.k8s.io/kustomize/kyaml/kio.(*ByteReader).Read(0xc000959d68)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/kio/byteio_reader.go:228 +0x371
sigs.k8s.io/kustomize/kyaml/kio.FromBytes({0xc000daa000, 0x895, 0x896})
    sigs.k8s.io/kustomize/kyaml@v0.13.9/kio/byteio_reader.go:110 +0xbb
sigs.k8s.io/kustomize/api/resource.(*Factory).RNodesFromBytes(0xc000fde360?, {0xc000daa000?, 0x26e0240?, 0x388af00?})
    sigs.k8s.io/kustomize/api@v0.12.1/resource/factory.go:167 +0x30
sigs.k8s.io/kustomize/api/resource.(*Factory).SliceFromBytes(0xc0010b5a90?, {0xc000daa000?, 0x1d?, 0x26ac368?})
    sigs.k8s.io/kustomize/api@v0.12.1/resource/factory.go:120 +0x38
github.com/fluxcd/pkg/kustomize.(*Generator).generateKustomization.func1.1({0xc0010b59a0, 0x4b}, {0x26d97c8?, 0xc000d0be10?}, {0x0?, 0x0?})
    github.com/fluxcd/pkg/kustomize@v0.12.0/kustomize_generator.go:451 +0x3e5
github.com/fluxcd/pkg/kustomize/filesys.fsSecure.Walk.func1({0xc0010b59a0, 0x4b}, {0x26d97c8, 0xc000d0be10}, {0x0, 0x0})
    github.com/fluxcd/pkg/kustomize@v0.12.0/filesys/fs_secure.go:241 +0x176
path/filepath.walk({0xc0010b59a0, 0x4b}, {0x26d97c8, 0xc000d0be10}, 0xc0002ce190)
    path/filepath/path.go:433 +0x123
path/filepath.walk({0xc000b3d180, 0x33}, {0x26d97c8, 0xc000e7a680}, 0xc0002ce190)
    path/filepath/path.go:457 +0x285
path/filepath.walk({0xc000346750, 0x2c}, {0x26d97c8, 0xc000f68a90}, 0xc0002ce190)
    path/filepath/path.go:457 +0x285
path/filepath.Walk({0xc000346750, 0x2c}, 0xc0002ce190)
    path/filepath/path.go:520 +0x6c
sigs.k8s.io/kustomize/kyaml/filesys.fsOnDisk.Walk(...)
    sigs.k8s.io/kustomize/kyaml@v0.13.9/filesys/fsondisk.go:138
github.com/fluxcd/pkg/kustomize/filesys.fsSecure.Walk({{0xc000fde360, 0x1d}, {0x26e0240, 0x388af00}, {0x0, 0x0, 0x0}}, {0xc000346750, 0x2c}, 0xc000b50340)
    github.com/fluxcd/pkg/kustomize@v0.12.0/filesys/fs_secure.go:243 +0xec
github.com/fluxcd/pkg/kustomize.(*Generator).generateKustomization.func1({0xc000346750, 0x2c})
    github.com/fluxcd/pkg/kustomize@v0.12.0/kustomize_generator.go:422 +0x151
github.com/fluxcd/pkg/kustomize.(*Generator).generateKustomization(0x1ebfd60?, {0xc000346750, 0x2c})
    github.com/fluxcd/pkg/kustomize@v0.12.0/kustomize_generator.go:465 +0x29b
github.com/fluxcd/pkg/kustomize.(*Generator).WriteFile(0xc00095bff8?, {0xc000346750, 0x2c}, {0x0, 0x0, 0x215e3c0?})
    github.com/fluxcd/pkg/kustomize@v0.12.0/kustomize_generator.go:112 +0x56
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).generate(0x384cec0?, {0x215e3c0?}, {0xc0005ba880?, 0xc0000f6f00?}, {0xc000346750?, 0x65?})
    github.com/fluxcd/kustomize-controller/controllers/kustomization_controller.go:559 +0x53
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).reconcile(0xc000cc8410, {0x26d43e8, 0xc0005bee70}, 0xc0000f6f00, {0x26d4810, 0xc000b0d680}, 0xc000a12970?)
    github.com/fluxcd/kustomize-controller/controllers/kustomization_controller.go:375 +0xc25
github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).Reconcile(0xc000cc8410, {0x26d43e8, 0xc0005bee70}, {{{0xc000a12970?, 0x10?}, {0xc000a12960?, 0x40dc67?}}})
    github.com/fluxcd/kustomize-controller/controllers/kustomization_controller.go:263 +0x985
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x26d4340?, {0x26d43e8?, 0xc0005bee70?}, {{{0xc000a12970?, 0x20ab920?}, {0xc000a12960?, 0x404554?}}})
    sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000ce4140, {0x26d4340, 0xc000caaec0}, {0x1f4bb00?, 0xc000426a80?})
    sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000ce4140, {0x26d4340, 0xc000caaec0})
    sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
    sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:230 +0x333
```

I'll understand if you close this as user error since clearly my regex is bad but I didn't figure it should crash this hard. I was unable to recover flux without running `flux uninstall` but I didn't try too hard to fix it before I ran the uninstall command.

### Steps to reproduce

Install flux and create a notification configuration like this:

```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: notifications
  address: https://hooks.slack.com/services/ABCD/EFGH
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: errors-to-slack
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: Bucket
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmChart
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: ImageRepository
      name: '*'
    - kind: ImagePolicy
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
  exclusionList:
    # ignore messages when something first enters the system
    - "version list argument cannot be empty"
    - "ImageRepository\.image\.toolkit\.fluxcd\.io \".*\" not found"
```

### Expected behavior

Maybe log an error?

### OS / Distro

k3s on Debian

### Flux version

0.38.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.4+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.28.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.32.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.30.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.33.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Additional context

Thanks for your help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This was fixed in Flux 0.39.0
